trailingComma: 'all'
tabWidth: 2
semi: false
singleQuote: true
bracketSameLine: true
plugins:
  - 'prettier-plugin-tailwindcss'
  - '@trivago/prettier-plugin-sort-imports'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - '^@(builder.io/|qwik)(.*)$'
  - '<THIRD_PARTY_MODULES>'
  - '^[./~]'
