name = "quiple-dev"
compatibility_date = "2025-05-21"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist/"
binding = "ASSETS"

[observability]
enabled = true

[limits]
cpu_ms = 300000

[vars]
KEYSTATIC_GITHUB_CLIENT_ID = "Iv23linT22YZnRWliZUm"
PUBLIC_KEYSTATIC_GITHUB_APP_SLUG = "quiple-keystatic"

CHZZK_CLIENTID = "f9bd31b8-3b11-4f86-9dc4-f959300d5740"
CHZZK_REDIRECTURI = "https://quiple.dev/chzzk/callback"
CHZZK_STATE = "quiple"
