name = "quiple-dev"
compatibility_date = "2025-05-21"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist/"
binding = "ASSETS"

[observability]
enabled = true
